# Generated by Django 4.2.3 on 2023-07-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('mobilenumber', models.IntegerField()),
            ],
        ),
    ]
