# Generated by Django 4.2.3 on 2023-08-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_area_appmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='join',
            field=models.DateField(null=True),
        ),
    ]
