# Generated by Django 4.2.3 on 2023-08-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appmodel_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litre', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('rate', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appmodel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
