# Generated by Django 4.2.3 on 2023-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='litre',
            field=models.FloatField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.FloatField(max_length=1000),
        ),
    ]
