# Generated by Django 4.2.3 on 2023-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_options_alter_article_litre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='litre',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.FloatField(max_length=100),
        ),
    ]
